### ISSUE TITLE
Servidores compatibles

### ISSUE THREAD

**Issue by alvarodevlabs** [lscofield/url-resolver-android-simple#1]
¡Hola!

¿Podrás hacer gamovideo.com, waaw.tv, aparat.cam y powvideo.net compatibles en Java?

¡Un saludo y gracias por este gran proyecto!

**Comment by lscofield** [comment]
Veré si es posible

**Comment by alvarodevlabs** [comment]
Han lanzado un nuevo server por si quieres echarle un vistazo :) https://playtubeapi.docs.apiary.io/ https://playtube.ws/ Un saludo!
